"""crear tablas iniciales

Revision ID: f140554ef40e
Revises: 
Create Date: 2026-04-28 20:49:50.825899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f140554ef40e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generos',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('libros',
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('editorial', sa.String(length=100), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('url_portada', sa.String(length=500), nullable=True),
    sa.Column('lenguaje', sa.String(length=2), nullable=False),
    sa.Column('num_paginas', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('libro_autores',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'autor_id')
    )
    op.create_table('libro_generos',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'genero_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libro_generos')
    op.drop_table('libro_autores')
    op.drop_table('libros')
    op.drop_table('generos')
    op.drop_table('autores')
    # ### end Alembic commands ###
